<?php
$escape = $this->plugin('escapeHtml');
?>
<div id="resource-template-selector" class='selector sidebar <?php echo $state; ?>'>
    <?php if ($text) :?>
    <h3><?php echo $escape($text); ?></h3>
    <?php else: ?>
    <h3><?php echo $this->translate('Click on a resource template to add it to the mapped item types.'); ?></h3>
    <?php endif; ?>
    <input type="text" class="selector-filter" placeholder="<?php echo $this->translate('Filter resource templates'); ?>" aria-label="<?php echo $this->translate('Filter resource templates'); ?>">
        <ul class='selectable-list'>
            <li class="selector-parent">
                <span><?php echo $escape($this->translate('Resource Templates')); ?></span> (<span class="selector-child-count"><?php echo count($templates); ?></span>)
                <ul>
                    <?php foreach ($templates as $template): ?>
                    <li class='selector-child'
                        data-child-search="<?php echo $escape($template->label()); ?>"
                        data-template-id="<?php echo $escape($template->id()); ?>">
                        <span><?php echo $escape($this->translate($template->label())); ?></span>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
</div>
