<a href='#' id='omeka2-import-elements-map' class='omeka2-import-fieldset-label'><?php echo $this->translate('Map Omeka 2 Elements to Omeka S Properties'); ?></a>
<?php print_r($elementDefaultMap); ?>
<fieldset id="omeka2-import-elements-map-fieldset">
    <table style="width: 60%">
        <thead>
            <tr>
                <th><?php echo $this->translate("Omeka 2 Element"); ?></th>
                <th><?php echo $this->translate("Mapped Properties"); ?></th>
                <th><?php echo $this->translate("Import as HTML Media"); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($elementsData as $name=>$elementSet): ?>
            <tr class="element-set">
                <th class="omeka2-importer element-set" colspan="3"><?php echo $name; ?></th>
            </tr>
            <?php foreach ($elementSet as $element): ?>
            <tr class="element mappable" data-element-id="<?php echo $element['id']; ?>">
                <td><?php echo $element['name'];?></td>
                <td class="mapping element">
                    <ul class="mappings elements">
                    <?php if(array_key_exists($name, $elementDefaultMap) 
                             && array_key_exists($element['name'], $elementDefaultMap[$name])):?>
                        <li class='mapping' data-property-id='<?php echo $element['id']; ?>'>
                            <?php echo $elementDefaultMap[$name][$element['name']]['propertyLabel']; ?>
                            <ul class="actions"><li><a aria-label="Remove mapping" title="Remove mapping" class="o-icon-delete remove-mapping" href="#" style="display: inline;"></a></li><li><a aria-label="Undo remove mapping" title="Undo remove mapping" class="o-icon-undo restore-mapping" href="#" style="display: none;"></a></li></ul>
                            <input type='hidden' name='element-property[<?php echo $element['id']; ?>][]' value='<?php echo $elementDefaultMap[$name][$element['name']]['propertyLabel']; ?>' />
                        </li>
                    <?php endif; ?>
                    </ul>
                </td>
                <td>
                    <input type="checkbox" name="element-html[<?php echo $element['id']; ?>]"></input>
                </td>
            </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</fieldset>

<a href='#' id='omeka2-import-types-map' class='omeka2-import-fieldset-label'>
<?php echo $this->translate('Map Omeka 2 Item Types to Omeka S Resource Classes'); ?>
</a>

<fieldset id="omeka2-import-types-map-fieldset">
    <p>
        <?php echo $this->translate('Items can have only one resource class. Clicking more than one resource class for an item type will replace it.'); ?>
    </p>
    <table style="width: 60%">
        <thead>
            <tr>
                <th><?php echo $this->translate('Item Type'); ?></th>
                <th><?php echo $this->translate('Resource Class'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($itemTypes as $itemType): ?><tr>
            <tr class="item-type mappable"  data-item-type-id="<?php echo $itemType['id']; ?>" >
                <td>
                    <?php echo $itemType['name']; ?>
                </td>
                <td class="mapping item-type">
                    <ul class="mappings item-types"></ul>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</fieldset>
