<?php 
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Import · Omeka 2 Importer')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElements($form); ?>
<?php 
$mappingUrl = $this->url('admin/omeka2importer/mapping',
              array('controller' => 'index', 'action' => 'mapping')
          );
?>
<a href='<?php echo $mappingUrl; ?>'>Continue to mappings</a>
<?php echo $this->form()->closeTag($form); ?>
