<?php 
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/omeka2importer.js', 'Omeka2Importer'));
$this->headLink()->appendStylesheet($this->assetUrl('css/omeka2importer.css', 'Omeka2Importer'));

?>

<?php echo $this->pageTitle($this->translate('Import · Omeka 2 Importer')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElements($form); ?>
<?php 
$mappingUrl = $this->url('admin/omeka2importer/mapping',
              array('controller' => 'index', 'action' => 'mapping')
          );
?>

<table style="width: 60%">
    <thead>
        <tr>
            <th><?php echo $this->translate("Omeka 2 Element"); ?></th>
            <th><?php echo $this->translate("Mapped Properties"); ?></th>
            <th><?php echo $this->translate("Import as HTML Media"); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($elementsData as $name=>$elementSet): ?>
        <tr class="element-set">
            <td colspan="3"><?php echo $name; ?></td>
        </tr>
        <?php foreach ($elementSet as $element): ?>
        <tr class="element" data-element-id="<?php echo $element['id']; ?>">
            <td><?php echo $element['name'];?></td>
            <td class="mapping">
                <ul class="mappings"></ul>
            </td>
            <td>
                <input type="checkbox" name="element-html[<?php echo $element['id']; ?>]"></input>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
<?php
        $propertySelectorHtml = $this->propertySelector('Select property to map');
        $classSelectorHtml = $this->resourceClassSelector('Select class to map');
?>
<?php echo $propertySelectorHtml; ?>
<?php echo $classSelectorHtml; ?>


<?php echo $this->form()->closeTag($form); ?>
